# Site
title: russtone.io
author: russtone
language: en
timezone: Europe/Moscow
description: Information security blog

# URL
url: http://russtone.io
root: /

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Skip
skip_render: [keybase.txt]

# Theme
theme: russtone

# SEO
sitemap:
  path: sitemap.xml

# Code highlight
highlight:
  enable: false

# Assets
post_asset_folder: true

# Deployment
deploy:
  type: rsync
  host: russtone.io
  port: 22
  user: russtone
  root: /var/www/russtone.io
  delete: true
  verbose: true
  ignore_errors: false
