# Site
title: russtone.io
author: russtone
language: en
timezone: Europe/Moscow

# URL
url: http://russtone.io
root: /

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Theme
theme: russtone

# Code highlight
highlight:
  enable: false

# Deployment
deploy:
  type: rsync
  host: russtone.io
  port: 22
  user: russtone
  root: /var/www/blog
  delete: true
  verbose: true
  ignore_errors: false
