menu:
  categories: Categories
  tags: Tags
  archive: Archive
  about: About

google_analytics: UA-81673589-1

contacts:
  twitter:
    icon: fa fa-twitter-square
    link: https://twitter.com/nt0x4
  github:
    icon: fa fa-github-square
    link: https://github.com/nt0xa
  linkedin:
    icon: fa fa-linkedin-square
    link: https://linkedin.com/in/prokhorov-anton-70168962
