menu:
  categories: Categories
  tags: Tags
  archive: Archive
  about: About

google_analytics: UA-81673589-1

disqus: //https-russtone-io.disqus.com/embed.js

contacts:
  twitter:
    icon: fa fa-twitter-square
    link: https://twitter.com/russt0ne
  github:
    icon: fa fa-github-square
    link: https://github.com/russtone
  linkedin:
    icon: fa fa-linkedin-square
    link: https://linkedin.com/in/prokhorov-anton-70168962
